### PR TITLE
Added Lambda module

### PR DESCRIPTION
**Pull request by teymurgahramanov**
It will:
- Create Lambda function
- Create an IAM role with the name of the Lambda function
- Create IAM Role Policy from the file you provided and attach it to the Role

### CODE REVIEW

**Review by corest — COMMENTED** [review]
What is supposed to call this?
Why there is such a strict rely on `terraform` folder and `refs/heads/v0` ref?

**Comment by teymurgahramanov** [comment]
terraform directory should contain IAM policy and terraform file to call this module

**Comment by teymurgahramanov** [comment]
Its related to this task
https://veegoteam.atlassian.net/browse/VEEGO-942

**Comment by teymurgahramanov** [comment]
Its related to this task
https://veegoteam.atlassian.net/browse/VEEGO-942

**Pull request closed without merging**
