### PR TITLE
DEVOPS-636: Add basic docker flow

### PR DESCRIPTION
**Pull request by vnhirenko**

### CODE REVIEW

**Review by corest — COMMENTED** [review]
Looks ok, but why do we need explicit workflow for this?

**Comment by hirenko-v** [comment]
@corest because we dont have something like this just to build and push image

**Comment by hirenko-v** [comment]
@corest we have workflow that builds app on the runner, push artifact top git then downloads artifact and does docker build but I'd like to have classic docker flow where alll that we need is just use dockerfile to build image

**Comment by corest** [comment]
@vnhirenko I still didn't get why do you need separate workflow instead of just calling `veegoteam/workflows/actions/build-push-docker@v1.8.0` where you need

**Comment by vnhirenko** [comment]
the idea was to reuse it in multiple repos in the future I will create it in the service repo then, thnx

**Pull request closed without merging**
